### ISSUE TITLE
Sejong bot has stopped functionning

### ISSUE THREAD

**Issue by nicokdo** [jarjumarvin/sejong-bot#9]
Dear Marvin, 

The Sejong bot has stopped functioning on my server NicoDico for some unknown reasons. I have tried to remove and reinstall it but it doesn't appear online anymore. Are you doing some maintenance?

Kindest regards

**Comment by jarjumarvin** [comment]
Hey sorry for the late response,

unfortunately there appears to be a fundamental issue due to some functionality in the discord.js framework being depreceated.

Currently I do not have the time to fix it due to exams and general lack of free time :( I've decided to just take the bot down indefinitely until I am able to fix it.

I hope you understand,
Marvin

**Comment by nicokdo** [comment]
Dear Marvin,

Thank you very much for your reply! 🙂
We were very worried about Sejong as it suddenly stopped functionning.

I wish you good luck for your exams and wish that Sejong will come back as soon as you are free again.

Please don't hesitate to keep me up to date.

Kindest regards,

Nicolas BRUNETEAU
 ( ブリュヌト・ニコラ | 布鲁诺多・尼古拉 (倪晓岚|倪曉嵐) |블르느토・니콜라)

NicoDico, Chinese (traditional & simplified), Korean, Japanese dictionary:
https://www.nicodico.net/
To further support NicoDico:
https://fr.tipeee.com/nicokdo

All my professional experiences are on Linkedin:
https://www.linkedin.com/in/nicolas-bruneteau-697569146/
All my books are on Lulu:
<https://www.linkedin.com/in/nicolas-bruneteau-697569146/>http://www.lulu.com/shop/search.ep?contributorId=1531487

________________________________
De : Marvin Jarju <notifications@github.com>
Envoyé : mercredi 3 février 2021 15:32
À : jarjumarvin/sejong-bot <sejong-bot@noreply.github.com>
Cc : nicokdo <nicobruneteau@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [jarjumarvin/sejong-bot] Sejong bot has stopped functionning (#9)


Hey sorry for the late response,

unfortunately there appears to be a fundamental issue due to some functionality in the discord.js framework being depreceated.

Currently I do not have the time to fix it due to exams and general lack of free time :( I've decided to just take the bot down indefinitely until I am able to fix it.

I hope you understand,
Marvin

**Comment by Fox-Islam** [comment]
Hi @jarjumarvin and @nicokdo - I've opened up a PR (https://github.com/jarjumarvin/sejong-bot/pull/10) with some images attached in the comments that I think addresses these issues to hopefully take some of the workload off you, if you get some time could you please look over the changes?
